services:
  gateway:
    build: .
    env_file:
      - ./gateway/.env  # Explicitly pointing to the subfolder
    ports:
      - "${APP_PORT}:5000"
    environment:
      - 
  
  inference_worker:
    build: .
    env_file:
      - ./inference_worker/.env 
    ports: 
      - "${GRPC_SERVER_PORT:50051}"