name: ml-inference

services:
  gateway:
    build: ./gateway
    env_file:
      - ./gateway/.env  # Explicitly pointing to the subfolder
    ports:
      - "${APP_PORT}:5000"
  
  inference_worker:
    build: 
      context: .
      dockerfile: ./inference_worker/Dockerfile
    ports: 
      - "${GRPC_SERVER_PORT}:50051"