FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

#cache the downloaded package files, to avoid future downloads
RUN pip install -no-cache-dir -r requirements.txt

COPY ..

CMD ["python", "main"]